source "http://rubygems.org"

gem "sinatra", :git => "git://github.com/sinatra/sinatra.git", :require => "sinatra/base"
gem "i18n", "~> 0.6.0"
gem "activesupport", "~> 3.1.3", :require => "active_support"
gem "sprockets", "~> 2.3.0"
gem "sprockets-helpers", "~> 0.2.1"
gem "less", "~> 2.0.8"
gem "haml", "~> 3.1.4"
gem "coffee-script", "~> 2.2.0"
gem "rinku", "~> 1.5.0"
gem "heroku", "~> 2.18.1"
gem "unicorn", "~> 4.3.1"
gem "pony", "~> 1.4"
gem "sinatra-flash", "~> 0.3.0", :require => "sinatra/flash"
